# Generated by Django 2.2.4 on 2019-08-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='daily_goal',
            field=models.IntegerField(default=0),
        ),
    ]
